# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evan Louie
email: evan.louie@microsoft.com
description: >
  The personal website of Evan Louie;
  developer, designer, photographer, fashionista, and drinker of beer.
logo: "/assets/images/logo.svg"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.evanlouie.com # the base hostname & protocol for your site
paginate:	6 # The number of posts to show per page on your homepage

name: Evan Louie
bio: >
  Evan is software developer who likes to eat, drink, and code.
  When he's not at the gym or just being lazy, he's usally coding something stupid in an attempt
  to either break the internet or just make it a little less broken.
  Evan is currently working as a Software Engineer at Microsoft on the Developer Experience (DX Corp) Team.
author_image: "/assets/images/author.jpg"
twitter_username: evanlouie
github_username:  evanlouie

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - tsconfig.json
  - vendor
