class Euler2
  @question = () ->
    '''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    '''

  @answer = () ->
    fibSequence = () ->
      prev = 0
      curr = 1
      loop
        yield curr
        next = prev + curr
        prev = curr
        curr = next
      return

    sum = 0
    for fib from fibSequence()
      if fib <= 4000000
        if fib % 2 is 0 then sum += fib
      else break

    return sum
