function l(c){var d=0;return function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}}}var q="function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,a){c!=Array.prototype&&c!=Object.prototype&&(c[d]=a.value)},t="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function u(){u=function(){};t.Symbol||(t.Symbol=w)}var w=function(){var c=0;return function(d){return"jscomp_symbol_"+(d||"")+c++}}();
function x(){u();var c=t.Symbol.iterator;c||(c=t.Symbol.iterator=t.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&q(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return y(l(this))}});x=function(){}}function y(c){x();c={next:c};c[t.Symbol.iterator]=function(){return this};return c}
function z(c,d){x();c instanceof String&&(c+="");var a=0,b={next:function(){if(a<c.length){var e=a++;return{value:d(e,c[e]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b}function A(c){if(c){for(var d=t,a=["Array","prototype","keys"],b=0;b<a.length-1;b++){var e=a[b];e in d||(d[e]={});d=d[e]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&q(d,a,{configurable:!0,writable:!0,value:c})}}
A(function(c){return c?c:function(){return z(this,function(d){return d})}});
(function(){(function(){(function(){this.H={fb:null!=window.history.pushState&&null!=window.requestAnimationFrame&&null!=window.addEventListener,za:function(d,a){return c.controller.za(d,a)},ca:function(){return c.controller.ca()},va:function(d){return c.controller.va(d)}}}).call(this)}).call(this);var c=this.H;(function(){(function(){var d=[].slice;c.Ga=function(b){var a;var e={};for(a in b){var f=b[a];e[a]=f}return e};c.closest=function(b,e){return a.call(b,e)};var a=function(){var b,a;return b=
document.documentElement,null!=(a=b.closest)?a:function(b){var a;for(a=this;a;){if(a.nodeType===Node.ELEMENT_NODE&&e.call(a,b))return a;a=a.parentNode}}}();c.defer=function(b){return setTimeout(b,1)};c.ud=function(b){var a;return a=null,function(){var e;return e=1<=arguments.length?d.call(arguments,0):[],null!=a?a:a=requestAnimationFrame(function(g){return function(){return a=null,b.apply(g,e)}}(this))}};c.l=function(a,e){var g,f,d,c,p,n;return p=null!=e?e:{},n=p.target,g=p.cancelable,f=p.data,d=
document.createEvent("Events"),d.initEvent(a,!0,!0===g),d.data=null!=f?f:{},d.cancelable&&!b&&(c=d.preventDefault,d.preventDefault=function(){return this.defaultPrevented||Object.defineProperty(this,"defaultPrevented",{get:function(){return!0}}),c.call(this)}),(null!=n?n:document).dispatchEvent(d),d};var b=function(){var b;return b=document.createEvent("Events"),b.initEvent("test",!0,!0),b.preventDefault(),b.defaultPrevented}();c.match=function(b,a){return e.call(b,a)};var e=function(){var b,a,e,
d;return b=document.documentElement,null!=(a=null!=(e=null!=(d=b.matchesSelector)?d:b.webkitMatchesSelector)?e:b.msMatchesSelector)?a:b.mozMatchesSelector}();c.ya=function(){var b,a;var e="";for(b=a=1;36>=a;b=++a)e+=9===b||14===b||19===b||24===b?"-":15===b?"4":20===b?(Math.floor(4*Math.random())+8).toString(16):Math.floor(15*Math.random()).toString(16);return e}}).call(this);(function(){c.Location=function(){function d(b){null==b&&(b="");var a=document.createElement("a");a.href=b.toString();this.f=
a.href;b=a.hash.length;2>b?this.X=this.f:(this.X=this.f.slice(0,-b),this.anchor=a.hash.slice(1))}var a,b,e,f;return d.i=function(b){return b instanceof this?b:new this(b)},d.prototype.hc=function(){return this.f.split("/",3).join("/")},d.prototype.La=function(){var b,a;return null!=(b=null!=(a=this.X.match(/\/\/[^\/]*(\/[^?;]*)/))?a[1]:void 0)?b:"/"},d.prototype.ic=function(){return this.La().split("/").slice(1)},d.prototype.bc=function(){return this.ic().slice(-1)[0]},d.prototype.getExtension=function(){var b,
a;return null!=(b=null!=(a=this.bc().match(/\.[^.]*$/))?a[0]:void 0)?b:""},d.prototype.Ac=function(){return this.getExtension().match(/^(?:|\.(?:htm|html|xhtml))$/)},d.prototype.Bc=function(a){var e;return e=b(a),this.Ra(a)||f(this.f,e)},d.prototype.Ra=function(b){return this.f===(null!=b?b.f:void 0)},d.prototype.toJSON=function(){return this.f},d.prototype.toString=function(){return this.f},d.prototype.valueOf=function(){return this.f},b=function(b){return a(b.hc()+b.La())},a=function(b){return e(b,
"/")?b:b+"/"},f=function(b,a){return b.slice(0,a.length)===a},e=function(b,a){return b.slice(-a.length)===a},d}()}).call(this);(function(){function d(a,b){return function(){return a.apply(b,arguments)}}c.Aa=function(){function a(b,a,f){this.b=b;this.na=d(this.na,this);this.ra=d(this.ra,this);this.oa=d(this.oa,this);this.qa=d(this.qa,this);this.A=d(this.A,this);this.url=c.Location.i(a).X;this.referrer=c.Location.i(f).f;this.Kb()}return a.Ba=0,a.Ea=-1,a.timeout=60,a.prototype.send=function(){var b;
return this.a&&!this.ab?(this.Qc(),this.ua(0),this.a.send(),this.ab=!0,"function"==typeof(b=this.b).Za?b.Za():void 0):void 0},a.prototype.cancel=function(){return this.a&&this.ab?this.a.abort():void 0},a.prototype.A=function(b){return b.lengthComputable?this.ua(b.loaded/b.total):void 0},a.prototype.qa=function(){return this.M(function(b){return function(){var a;return 200<=(a=b.a.status)&&300>a?b.b.dd(b.a.responseText,b.a.getResponseHeader("Turbolinks-Location")):(b.fa=!0,b.b.pa(b.a.status,b.a.responseText))}}(this))},
a.prototype.oa=function(){return this.M(function(b){return function(){return b.fa=!0,b.b.pa(b.constructor.Ba)}}(this))},a.prototype.ra=function(){return this.M(function(b){return function(){return b.fa=!0,b.b.pa(b.constructor.Ea)}}(this))},a.prototype.na=function(){return this.M()},a.prototype.Qc=function(){c.l("turbolinks:request-start",{data:{url:this.url,a:this.a}})},a.prototype.Mc=function(){c.l("turbolinks:request-end",{data:{url:this.url,a:this.a}})},a.prototype.Kb=function(){this.a=new XMLHttpRequest;
this.a.open("GET",this.url,!0);this.a.timeout=1E3*this.constructor.timeout;this.a.setRequestHeader("Accept","text/html, application/xhtml+xml");this.a.setRequestHeader("Turbolinks-Referrer",this.referrer);this.a.onprogress=this.A;this.a.onload=this.qa;this.a.onerror=this.oa;this.a.ontimeout=this.ra;this.a.onabort=this.na},a.prototype.M=function(b){return this.a?(this.Mc(),null!=b&&b.call(this),this.Mb()):void 0},a.prototype.ua=function(b){var a;return this.U=b,"function"==typeof(a=this.b).A?a.A(this.U):
void 0},a.prototype.Mb=function(){var b;return this.ua(1),"function"==typeof(b=this.b).Ya&&b.Ya(),this.b=null,this.a=null},a}()}).call(this);(function(){function d(a,b){return function(){return a.apply(b,arguments)}}c.qb=function(){function a(){this.xa=d(this.xa,this);this.td=this.Ib();this.o=this.Hb()}return a.Lb=".turbolinks-progress-bar {\n  position: fixed;\n  display: block;\n  top: 0;\n  left: 0;\n  height: 3px;\n  background: #0076ff;\n  z-index: 9999;\n  transition: width 300ms ease-out, opacity 150ms 150ms ease-in;\n  transform: translate3d(0, 0, 0);\n}",
a.prototype.show=function(){return this.visible?void 0:(this.visible=!0,this.xc(),this.wc(),this.pd())},a.prototype.tc=function(){this.visible&&!this.Qa&&(this.Qa=!0,this.Ob(function(b){return function(){return b.xd(),b.sd(),b.visible=!1,b.Qa=!1}}(this)))},a.prototype.wa=function(b){return this.value=b,this.refresh()},a.prototype.xc=function(){document.head.insertBefore(this.td,document.head.firstChild)},a.prototype.wc=function(){this.o.style.width=0;this.o.style.opacity=1;document.documentElement.insertBefore(this.o,
document.body);this.refresh()},a.prototype.Ob=function(b){this.o.style.opacity=0;setTimeout(b,450)},a.prototype.xd=function(){this.o.parentNode&&document.documentElement.removeChild(this.o)},a.prototype.pd=function(){return null!=this.aa?this.aa:this.aa=setInterval(this.xa,300)},a.prototype.sd=function(){clearInterval(this.aa);this.aa=null},a.prototype.xa=function(){return this.wa(this.value+Math.random()/100)},a.prototype.refresh=function(){return requestAnimationFrame(function(b){return function(){return b.o.style.width=
10+90*b.value+"%"}}(this))},a.prototype.Ib=function(){var b;return b=document.createElement("style"),b.type="text/css",b.textContent=this.constructor.Lb,b},a.prototype.Hb=function(){var b;return b=document.createElement("div"),b.className="turbolinks-progress-bar",b},a}()}).call(this);(function(){function d(a,b){return function(){return a.apply(b,arguments)}}c.mb=function(){function a(b){this.controller=b;this.Z=d(this.Z,this);this.V=new c.qb}var b,e,f;return f=c.Aa,b=f.Ba,e=f.Ea,a.prototype.Dd=function(b,
a){return this.controller.qd(b,a)},a.prototype.Gd=function(b){return b.Ec(),b.Cb(),b.Fc()},a.prototype.lb=function(b){return this.V.wa(0),b.Pa()||"restore"!==b.action?this.md():this.Z()},a.prototype.kb=function(b){return this.V.wa(b.U)},a.prototype.Ed=function(b){return b.Ta()},a.prototype.Fd=function(a,f){switch(f){case b:case e:return this.reload();default:return a.Ta()}},a.prototype.jb=function(){this.uc()},a.prototype.ba=function(b){return b.Tb()},a.prototype.Wa=function(){return this.reload()},
a.prototype.md=function(){return this.Vc=setTimeout(this.Z,this.controller.Uc)},a.prototype.Z=function(){return this.V.show()},a.prototype.uc=function(){this.V.tc();clearTimeout(this.Vc)},a.prototype.reload=function(){return window.location.reload()},a}()}).call(this);(function(){function d(a,b){return function(){return a.apply(b,arguments)}}c.History=function(){function a(b){this.b=b;this.S=d(this.S,this);this.T=d(this.T,this)}return a.prototype.start=function(){return this.j?void 0:(addEventListener("popstate",
this.T,!1),addEventListener("load",this.S,!1),this.j=!0)},a.prototype.stop=function(){return this.j?(removeEventListener("popstate",this.T,!1),removeEventListener("load",this.S,!1),this.j=!1):void 0},a.prototype.push=function(b,a){return b=c.Location.i(b),this.update("push",b,a)},a.prototype.replace=function(b,a){return b=c.Location.i(b),this.update("replace",b,a)},a.prototype.T=function(b){var a,f,d,h;return this.kd()&&(h=null!=(f=b.state)?f.wd:void 0)?(a=c.Location.i(window.location),d=h.h,this.b.vc(a,
d)):void 0},a.prototype.S=function(){return c.defer(function(b){return function(){return b.w=!0}}(this))},a.prototype.kd=function(){return this.Sc()},a.prototype.Sc=function(){return this.w||"complete"===document.readyState},a.prototype.update=function(b,a,f){var e;return e={wd:{h:f}},history[b+"State"](e,null,a)},a}()}).call(this);(function(){c.pb=function(){function d(b){var a,e,d,g;this.elements={};var h=0;for(g=b.length;g>h;h++){var m=b[h];m.nodeType===Node.ELEMENT_NODE&&(d=m.outerHTML,e=null!=
(a=this.elements)[d]?a[d]:a[d]={type:c(m),ib:f(m),elements:[]},e.elements.push(m))}}var a,b,e,f,c;return d.Wb=function(b){var a;return new this(null!=(a=null!=b?b.childNodes:void 0)?a:[])},d.prototype.sc=function(b){return b in this.elements},d.prototype.Oa=function(){var b,a;var e=this.elements;var d=[];for(b in e)(a=e[b].ib)&&d.push(b);return d.join("")},d.prototype.mc=function(b){return this.Ka("script",b)},d.prototype.nc=function(b){return this.Ka("stylesheet",b)},d.prototype.Ka=function(b,a){var e;
var d=this.elements;var f=[];for(e in d){var c=d[e];var g=c.type;c=c.elements;g!==b||a.sc(e)||f.push(c[0])}return f},d.prototype.Na=function(){var b;var a=[];var e=this.elements;for(b in e){var d=e[b];var f=d.type;var c=d.ib;d=d.elements;null!=f||c?1<d.length&&a.push.apply(a,d.slice(1)):a.push.apply(a,d)}return a},d.prototype.cc=function(b){var a;return null!=(a=this.Rb(b))?a.getAttribute("content"):void 0},d.prototype.Rb=function(b){var e;var d=void 0;var f=this.elements;for(e in f){var c=f[e].elements;
a(c[0],b)&&(d=c[0])}return d},c=function(a){return b(a)?"script":e(a)?"stylesheet":void 0},f=function(b){return"reload"===b.getAttribute("data-turbolinks-track")},b=function(b){var a;return a=b.tagName.toLowerCase(),"script"===a},e=function(b){var a;return a=b.tagName.toLowerCase(),"style"===a||"link"===a&&"stylesheet"===b.getAttribute("rel")},a=function(b,a){var e;return e=b.tagName.toLowerCase(),"meta"===e&&b.getAttribute("name")===a},d}()}).call(this);(function(){c.Da=function(){function d(a,b){this.O=
a;this.s=b}return d.i=function(a){return a instanceof this?a:"string"==typeof a?this.Vb(a):this.ga(a)},d.Vb=function(a){var b;return b=document.createElement("html"),b.innerHTML=a,this.ga(b)},d.ga=function(a){var b,e,d,g;return d=a.querySelector("head"),b=null!=(g=a.querySelector("body"))?g:document.createElement("body"),e=c.pb.Wb(d),new this(e,b)},d.prototype.clone=function(){return new this.constructor(this.O,this.s.cloneNode(!0))},d.prototype.ia=function(){var a,b;return b=null!=(a=this.ja("root"))?
a:"/",new c.Location(b)},d.prototype.Ia=function(){return this.ja("cache-control")},d.prototype.N=function(a){try{return this.s.querySelector("[id='"+a+"'], a[name='"+a+"']")}catch(b){}},d.prototype.jc=function(){return this.s.querySelectorAll("[id][data-turbolinks-permanent]")},d.prototype.Ma=function(a){return this.s.querySelector("#"+a+"[data-turbolinks-permanent]")},d.prototype.kc=function(a){var b;var e=this.jc();var d=[];var c=0;for(b=e.length;b>c;c++){var h=e[c];a.Ma(h.id)&&d.push(h)}return d},
d.prototype.Qb=function(){return this.s.querySelector("[autofocus]")},d.prototype.rc=function(a){return null!=this.N(a)},d.prototype.Cc=function(){return"no-preview"!==this.Ia()},d.prototype.zc=function(){return"no-cache"!==this.Ia()},d.prototype.Dc=function(){return"reload"!==this.ja("visit-control")},d.prototype.ja=function(a){return this.O.cc("turbolinks-"+a)},d}()}).call(this);(function(){var d=[].slice;c.Ca=function(){function a(){}var b;return a.g=function(){var b,a,c,h;return c=arguments[0],
a=arguments[1],b=3<=arguments.length?d.call(arguments,2):[],h=function(b,a,e){e.prototype=b.prototype;e=new e;b=b.apply(e,a);return Object(b)===b?b:e}(this,b,function(){}),h.b=c,h.g(a),h},a.prototype.Xa=function(b){return this.b.Bd(this.u),b(),this.b.Ad()},a.prototype.yc=function(){return this.b.zd()},a.prototype.da=function(a){var e;return"false"===a.getAttribute("data-turbolinks-eval")?a:(e=document.createElement("script"),e.textContent=a.textContent,e.async=!1,b(e,a),e)},b=function(b,a){var e;
var d=a.attributes;var c=[];a=0;for(e=d.length;e>a;a++){var f=d[a];var k=f.name;f=f.value;c.push(b.setAttribute(k,f))}return c},a}()}).call(this);(function(){function d(b,e){function d(){this.constructor=b}for(var c in e)a.call(e,c)&&(b[c]=e[c]);return d.prototype=e.prototype,b.prototype=new d,b.wb=e.prototype,b}var a={}.hasOwnProperty;c.tb=function(a){function c(b,a,e){this.Ha=b;this.v=a;this.la=e;this.L=this.Ha.O;this.R=this.v.O;this.u=this.v.s}return d(c,a),c.prototype.g=function(b){return this.ld()?
(this.Hc(),this.Xa(function(a){return function(){return a.$c(),a.la||a.Sb(),b()}}(this))):this.yc()},c.prototype.Hc=function(){this.Gb();this.Fb();this.Xc();this.Eb()},c.prototype.$c=function(){var b=this.Wc();this.yb();this.Bb();this.cd(b)},c.prototype.ld=function(){return this.v.Dc()&&this.vd()},c.prototype.vd=function(){return this.L.Oa()===this.R.Oa()},c.prototype.Gb=function(){var b;var a=this.gc();var e=[];var c=0;for(b=a.length;b>c;c++){var d=a[c];e.push(document.head.appendChild(d))}},c.prototype.Fb=
function(){var b;var a=this.fc();var e=[];var c=0;for(b=a.length;b>c;c++){var d=a[c];e.push(document.head.appendChild(this.da(d)))}},c.prototype.Xc=function(){var b;var a=this.$b();var e=[];var c=0;for(b=a.length;b>c;c++){var d=a[c];e.push(document.head.removeChild(d))}},c.prototype.Eb=function(){var b;var a=this.ec();var e=[];var c=0;for(b=a.length;b>c;c++){var d=a[c];e.push(document.head.appendChild(d))}},c.prototype.Wc=function(){var a;var c=this.Zb();var d=[];var f=0;for(a=c.length;a>f;f++){var g=
c[f];var n=b(g);var m=this.v.Ma(g.id);e(g,n.element);e(m,g);d.push(n)}return d},c.prototype.cd=function(b){var a;var c=[];var d=0;for(a=b.length;a>d;d++){var f=b[d];var g=f.element;f=f.Tc;f=f.cloneNode(!0);c.push(e(g,f))}},c.prototype.yb=function(){var b;var a=this.dc();var c=[];var d=0;for(b=a.length;b>d;d++){var f=a[d];var g=this.da(f);c.push(e(f,g))}},c.prototype.Bb=function(){document.body=this.u},c.prototype.Sb=function(){var b;null!=(b=this.v.Qb())&&b.focus()},c.prototype.gc=function(){return this.R.nc(this.L)},
c.prototype.fc=function(){return this.R.mc(this.L)},c.prototype.$b=function(){return this.L.Na()},c.prototype.ec=function(){return this.R.Na()},c.prototype.Zb=function(){return this.Ha.kc(this.v)},c.prototype.dc=function(){return this.u.querySelectorAll("script")},c}(c.Ca);var b=function(b){var a;return a=document.createElement("meta"),a.setAttribute("name","turbolinks-permanent-placeholder"),a.setAttribute("content",b.id),{element:a,Tc:b}};var e=function(b,a){var e;return(e=b.parentNode)?e.replaceChild(a,
b):void 0}}).call(this);(function(){function d(b,e){function c(){this.constructor=b}for(var d in e)a.call(e,d)&&(b[d]=e[d]);return c.prototype=e.prototype,b.prototype=new c,b.wb=e.prototype,b}var a={}.hasOwnProperty;c.ob=function(b){function a(b){var a=document.createElement("html");a.innerHTML=b;this.Ic=a.querySelector("head");this.u=a.querySelector("body")}return d(a,b),a.prototype.g=function(b){return this.Xa(function(a){return function(){return a.ad(),a.xb(),b()}}(this))},a.prototype.ad=function(){var b=
document.head;var a=document.body;b.parentNode.replaceChild(this.Ic,b);a.parentNode.replaceChild(this.u,a)},a.prototype.xb=function(){var b;var a=this.lc();var e=[];var c=0;for(b=a.length;b>c;c++){var d=a[c];var k=this.da(d);e.push(d.parentNode.replaceChild(k,d))}},a.prototype.lc=function(){return document.documentElement.querySelectorAll("script")},a}(c.Ca)}).call(this);(function(){c.ub=function(){function d(a){this.b=a;this.ka=document.documentElement}return d.prototype.ia=function(){return this.C().ia()},
d.prototype.N=function(a){return this.C().N(a)},d.prototype.C=function(){return c.Da.ga(this.ka)},d.prototype.g=function(a,b){var e,c,d;return d=a.cb,e=a.error,c=a.la,this.Gc(c),null!=d?this.Zc(d,c,b):this.Yc(e,b)},d.prototype.Gc=function(a){a?this.ka.setAttribute("data-turbolinks-preview",""):this.ka.removeAttribute("data-turbolinks-preview")},d.prototype.Zc=function(a,b,e){return c.tb.g(this.b,e,this.C(),c.Da.i(a),b)},d.prototype.Yc=function(a,b){return c.ob.g(this.b,b,a)},d}()}).call(this);(function(){function d(a,
b){return function(){return a.apply(b,arguments)}}c.rb=function(){function a(b){this.b=b;this.m=d(this.m,this);this.m=c.ud(this.m)}return a.prototype.start=function(){return this.j?void 0:(addEventListener("scroll",this.m,!1),this.m(),this.j=!0)},a.prototype.stop=function(){return this.j?(removeEventListener("scroll",this.m,!1),this.j=!1):void 0},a.prototype.ta=function(b){return b.scrollIntoView()},a.prototype.F=function(b){var a,c;return a=b.x,c=b.y,window.scrollTo(a,c)},a.prototype.m=function(){return this.yd()},
a.prototype.yd=function(){var b;return this.position={x:window.pageXOffset,y:window.pageYOffset},null!=(b=this.b)?b.fd(this.position):void 0},a}()}).call(this);(function(){c.sb=function(){function d(b){this.size=b;this.keys=[];this.$={}}var a;return d.prototype.has=function(b){var e;return e=a(b),e in this.$},d.prototype.get=function(b){var a;if(this.has(b))return a=this.read(b),this.hb(b),a},d.prototype.put=function(b,a){return this.write(b,a),this.hb(b),a},d.prototype.read=function(b){var e;return e=
a(b),this.$[e]},d.prototype.write=function(b,e){var c;return c=a(b),this.$[c]=e},d.prototype.hb=function(b){var e=a(b);b=this.keys.indexOf(e);-1<b&&this.keys.splice(b,1);this.keys.unshift(e);this.trim()},d.prototype.trim=function(){var b;var a=this.keys.splice(this.size);var c=[];var d=0;for(b=a.length;b>d;d++){var h=a[d];c.push(delete this.$[h])}return c},a=function(b){return c.Location.i(b).X},d}()}).call(this);(function(){function d(a,b){return function(){return a.apply(b,arguments)}}c.vb=function(){function a(b,
a,g){this.controller=b;this.action=g;this.D=d(this.D,this);this.identifier=c.ya();this.location=c.Location.i(a);this.c=this.controller.c;this.state="initialized";this.gb={}}var b;return a.prototype.start=function(){return"initialized"===this.state?(this.W("visitStart"),this.state="started",this.c.Gd(this)):void 0},a.prototype.cancel=function(){var b;return"started"===this.state?(null!=(b=this.request)&&b.cancel(),this.Fa(),this.state="canceled"):void 0},a.prototype.complete=function(){var b;return"started"===
this.state?(this.W("visitEnd"),this.state="completed","function"==typeof(b=this.c).ba&&b.ba(this),this.controller.ba(this)):void 0},a.prototype.Pb=function(){var b;return"started"===this.state?(this.state="failed","function"==typeof(b=this.c).Cd?b.Cd(this):void 0):void 0},a.prototype.Cb=function(){var a,c;this.P||(a=this.location.Ra(this.referrer)?"replace":this.action,c=b(a),this.controller[c](this.location,this.h),this.P=!0)},a.prototype.Ec=function(){this.bb()&&null==this.request&&(this.U=0,this.request=
new c.Aa(this,this.location,this.referrer),this.request.send())},a.prototype.Ja=function(){var b;return!(b=this.controller.Yb(this.location))||null!=this.location.anchor&&!b.rc(this.location.anchor)||"restore"!==this.action&&!b.Cc()?void 0:b},a.prototype.Pa=function(){return null!=this.Ja()},a.prototype.Fc=function(){var b,a;return(a=this.Ja())?(b=this.bb(),this.g(function(){var c;return this.I(),this.controller.g({cb:a,la:b},this.D),"function"==typeof(c=this.c).G&&c.G(this),b?void 0:this.complete()})):
void 0},a.prototype.Ta=function(){return null!=this.response?this.g(function(){var b,a;return this.I(),this.request.fa?(this.controller.g({error:this.response},this.D),"function"==typeof(b=this.c).G&&b.G(this),this.Pb()):(this.controller.g({cb:this.response},this.D),"function"==typeof(a=this.c).G&&a.G(this),this.complete())}):void 0},a.prototype.Tb=function(){return this.ma&&!this.Ub?(this.location=this.ma,this.controller.bd(this.ma,this.h),this.Ub=!0):void 0},a.prototype.Za=function(){var b;return this.W("requestStart"),
"function"==typeof(b=this.c).lb?b.lb(this):void 0},a.prototype.A=function(b){var a;return this.U=b,"function"==typeof(a=this.c).kb?a.kb(this):void 0},a.prototype.dd=function(b,a){return this.response=b,null!=a&&(this.ma=c.Location.i(a)),this.c.Ed(this)},a.prototype.pa=function(b,a){return this.response=a,this.c.Fd(this,b)},a.prototype.Ya=function(){var b;this.W("requestEnd");"function"==typeof(b=this.c).jb&&b.jb()},a.prototype.D=function(){return this.hd?void 0:("restore"===this.action?this.gd()||
this.$a():this.sa()||this.$a(),this.hd=!0)},a.prototype.gd=function(){var b,a;return b=null!=(a=this.B)?a.ed:void 0,null!=b?(this.controller.F(b),!0):void 0},a.prototype.sa=function(){return null!=this.location.anchor?(this.controller.sa(this.location.anchor),!0):void 0},a.prototype.$a=function(){this.controller.F({x:0,y:0})},a.prototype.W=function(b){var a;null!=(a=this.gb)[b]||(a[b]=(new Date).getTime())},a.prototype.oc=function(){return c.Ga(this.gb)},b=function(b){switch(b){case "replace":return"replaceHistoryWithLocationAndRestorationIdentifier";
case "advance":case "restore":return"pushHistoryWithLocationAndRestorationIdentifier"}},a.prototype.bb=function(){return"restore"===this.action?!this.Pa():!0},a.prototype.I=function(){this.nd||(this.controller.I(),this.nd=!0)},a.prototype.g=function(b){return this.Fa(),this.frame=requestAnimationFrame(function(a){return function(){return a.frame=null,b.call(a)}}(this))},a.prototype.Fa=function(){this.frame&&cancelAnimationFrame(this.frame)},a}()}).call(this);(function(){function d(a,b){return function(){return a.apply(b,
arguments)}}c.nb=function(){function a(){this.J=d(this.J,this);this.K=d(this.K,this);this.w=d(this.w,this);this.history=new c.History(this);this.view=new c.ub(this);this.Y=new c.rb(this);this.B={};this.ca();this.va(500)}return a.prototype.start=function(){return c.fb&&!this.j?(addEventListener("click",this.K,!0),addEventListener("DOMContentLoaded",this.w,!1),this.Y.start(),this.od(),this.j=!0,this.enabled=!0):void 0},a.prototype.stop=function(){return this.j?(removeEventListener("click",this.K,!0),
removeEventListener("DOMContentLoaded",this.w,!1),this.Y.stop(),this.rd(),this.j=!1):void 0},a.prototype.ca=function(){return this.cache=new c.sb(10)},a.prototype.za=function(b,a){var d,e;return null==a&&(a={}),b=c.Location.i(b),this.Ab(b)?this.Ua(b)?(d=null!=(e=a.action)?e:"advance",this.c.Dd(b,d)):window.location=b:void 0},a.prototype.qd=function(b,a){var d;return c.fb?(d=this.ha(void 0),this.eb(b,a,{B:d})):window.location=b},a.prototype.va=function(b){return this.Uc=b},a.prototype.od=function(){this.location=
c.Location.i(window.location);this.h=c.ya();this.history.start();this.history.replace(this.location,this.h)},a.prototype.rd=function(){this.history.stop()},a.prototype.bd=function(b,a){this.h=a;this.location=c.Location.i(b);this.history.replace(this.location,this.h)},a.prototype.vc=function(b,a){var d;return this.h=a,this.enabled?(d=this.ha(this.h),this.eb(b,"restore",{h:this.h,B:d,P:!0}),this.location=c.Location.i(b)):this.c.Wa()},a.prototype.Yb=function(b){var a;return null!=(a=this.cache.get(b))?
a.clone():void 0},a.prototype.jd=function(){return this.view.C().zc()},a.prototype.I=function(){var b,a;this.jd()&&(this.Oc(),a=this.view.C(),b=this.Sa,c.defer(function(c){return function(){return c.cache.put(b,a.clone())}}(this)))},a.prototype.sa=function(b){var a;return(a=this.view.N(b))?this.ta(a):this.F({x:0,y:0})},a.prototype.ta=function(b){return this.Y.ta(b)},a.prototype.F=function(b){return this.Y.F(b)},a.prototype.fd=function(b){var a;return a=this.ac(),a.ed=b},a.prototype.g=function(b,a){return this.view.g(b,
a)},a.prototype.zd=function(){return this.c.Wa()},a.prototype.Bd=function(b){this.Pc(b)},a.prototype.Ad=function(){return this.Sa=this.ea.location,this.Lc()},a.prototype.w=function(){return this.Sa=this.location,this.Va()},a.prototype.K=function(){return removeEventListener("click",this.J,!1),addEventListener("click",this.J,!1)},a.prototype.J=function(b){var a,c,d;return this.enabled&&this.Db(b)&&(c=this.pc(b.target))&&(d=this.qc(c))&&this.zb(c,d)?(b.preventDefault(),a=this.Xb(c),this.za(d,{action:a})):
void 0},a.prototype.zb=function(b,a){var c;return c=this.Kc(b,a),!c.defaultPrevented},a.prototype.Ab=function(b){var a;return a=this.Rc(b),!a.defaultPrevented},a.prototype.Kc=function(b,a){return c.l("turbolinks:click",{target:b,data:{url:a.f},cancelable:!0})},a.prototype.Rc=function(b){return c.l("turbolinks:before-visit",{data:{url:b.f},cancelable:!0})},a.prototype.Nc=function(b){return c.l("turbolinks:visit",{data:{url:b.f}})},a.prototype.Oc=function(){c.l("turbolinks:before-cache")},a.prototype.Pc=
function(b){c.l("turbolinks:before-render",{data:{u:b}})},a.prototype.Lc=function(){return c.l("turbolinks:render")},a.prototype.Va=function(b){return null==b&&(b={}),c.l("turbolinks:load",{data:{url:this.location.f,timing:b}})},a.prototype.eb=function(b,a,c){var d;return null!=(d=this.ea)&&d.cancel(),this.ea=this.Jb(b,a,c),this.ea.start(),this.Nc(b)},a.prototype.Jb=function(b,a,d){var e,f,v,r,k;return f=null!=d?d:{},r=f.h,v=f.B,e=f.P,k=new c.vb(this,b,a),k.h=null!=r?r:c.ya(),k.B=c.Ga(v),k.P=e,k.referrer=
this.location,k},a.prototype.ba=function(b){return this.Va(b.oc())},a.prototype.Db=function(b){return!(b.defaultPrevented||b.target.isContentEditable||1<b.which||b.altKey||b.ctrlKey||b.metaKey||b.shiftKey)},a.prototype.pc=function(b){return this.Jc(b)?c.closest(b,"a[href]:not([target]):not([download])"):void 0},a.prototype.qc=function(b){var a;return a=new c.Location(b.getAttribute("href")),this.Ua(a)?a:void 0},a.prototype.Xb=function(a){var b;return null!=(b=a.getAttribute("data-turbolinks-action"))?
b:"advance"},a.prototype.Jc=function(a){var b;return(b=c.closest(a,"[data-turbolinks]"))?"false"!==b.getAttribute("data-turbolinks"):!0},a.prototype.Ua=function(a){return a.Bc(this.view.ia())&&a.Ac()},a.prototype.ac=function(){return this.ha(this.h)},a.prototype.ha=function(a){var b;return null!=(b=this.B)[a]?b[a]:b[a]={}},a}()}).call(this);(function(){var c;a:{var a;if((c=a=document.currentScript)&&!a.hasAttribute("data-turbolinks-suppress-warning"))for(;c=c.parentNode;)if(c===document.body){c=console.warn("You are loading Turbolinks from a <script> element inside the <body> element. This is probably not what you meant to do!\n\nLoad your application\u2019s JavaScript bundle inside the <head> element instead. <script> elements in <body> are evaluated with each page change.\n\nFor more information, see: https://github.com/turbolinks/turbolinks#working-with-script-elements\n\n\u2014\u2014\nSuppress this warning by adding a `data-turbolinks-suppress-warning` attribute to: %s",
a.outerHTML);break a}c=void 0}!c}).call(this);(function(){c.start=function(){return d()?(null==c.controller&&(c.controller=a()),c.controller.start()):void 0};var d=function(){return null==window.H&&(window.H=c),b()};var a=function(){var a;return a=new c.nb,a.c=new c.mb(a),a};var b=function(){return window.H===c};b()&&c.start()}).call(this)}).call(this);"object"==typeof module&&module.Nb?module.Nb=c:"function"==typeof define&&define.Hd&&define(c)}).call(this);
